# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0024_auto_20160216_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('books', models.FileField(upload_to=b'course_help/(?P<course>[A-Z]+/books/')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='handout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handout', models.FileField(upload_to=b'course_help/(?P<course>[A-Z]+/handout/')),
                ('title', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.course')),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.FileField(upload_to=b'course_help/(?P<course>[A-Z]+)/notes/')),
                ('chapter', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.course')),
            ],
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'permissions': (('problem_solve', 'Solve problems SU'),)},
        ),
        migrations.AddField(
            model_name='books',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.course'),
        ),
    ]
