# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0025_auto_20160422_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='books',
            field=models.FileField(upload_to=b'books/'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='handout',
            field=models.FileField(upload_to=b'handout/'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notes',
            field=models.FileField(upload_to=b'notes/'),
        ),
    ]
